/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : PowerMgt 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"

#include "PowerMgt.h"

// Implemetation of void globals_PowerMgt()


#include <signal.h>

interrupt (WDT_VECTOR) watchdog_timer(void)
{
  __bic_SR_register_on_exit(LPM3_bits);     // Clear LPM3 bits from 0(SR)
}



void init_PowerMgt() {
// Implemetation of void init_PowerMgt()

	// WDTPW: The password. Any write without it generates a reset
	// WDTTMSEL: Set the watchdog to interval timer
	// WDTCNTCL: Reset the timer to 0x0000
	// WDTSSEL: Clock source to ACLK
	WDTCTL =WDTPW+WDTTMSEL+WDTCNTCL+WDTSSEL;
	BCSCTL3 |= LFXT1S_2;                      // ACLK = VLO (about 12kHz)
	BCSCTL1 |= DIVA_1;                        // ACLK/2
	IE1 |= WDTIE; // Enable WDT interrupt

}

void PowerMgt_send_sleep_about5s() {
// Implemetation of void PowerMgt_send_sleep_about5s()

	WDTCTL =WDTPW+WDTTMSEL+WDTCNTCL+WDTSSEL;
	IE1 |= WDTIE; // Enable WDT interrupt
	__bis_SR_register(LPM3_bits + GIE);

}
void PowerMgt_send_reset() {
// Implemetation of void PowerMgt_send_reset()

	WDTCTL = 0; // Write this register with incorect pw generates a reset

}
