
/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : Sensor 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"


#include  "msp430x22x4.h"
#include <signal.h>
#include <stdlib.h>
#include <string.h>


/******************************************************************************
 *                           INCLUDE THE DEVICES
 ******************************************************************************/
 
#include "LED.h" 
#include "Timer.h" 
#include "RF2500.h" 
#include "PowerMgt.h" 
#include "MSP430Sensor.h" 

/******************************************************************************
 *                      CODE FROM THE GLOBALS TEMPLATE
 ******************************************************************************/



char name[8];

static int temp;
static int batt;

static int sensor_id;
static char buf[16];



/******************************************************************************
 *                            STATES DECLARATION
 ******************************************************************************/
// Define all the states and their IDs
#define EDAP_STATE_SENSOR_0 0	// fixed
#define EDAP_STATE_INIT_2 2
#define EDAP_STATE_CONTACT_GATEWAY_3 3
#define EDAP_STATE_ACTIVE_1 1
#define EDAP_STATE_WAITING_4 4
#define EDAP_STATE_READSENSORVALUES_5 5

// Static variable to store the current state of the state machines and composites
static int EDAP_STATE_SENSOR_0_Current_State[2];

/******************************************************************************
 *                          PROTOTYPES DECLARATION
 ******************************************************************************/

// Prototypes for Entry actions
void EDAP_STATE_SENSOR_0_EDAP_STATE_INIT_2_On_Entry();
void EDAP_STATE_SENSOR_0_EDAP_STATE_CONTACT_GATEWAY_3_On_Entry();
void EDAP_STATE_SENSOR_0_EDAP_STATE_ACTIVE_1_On_Entry();
void EDAP_STATE_SENSOR_0_EDAP_STATE_WAITING_4_On_Entry();
void EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Entry();

// Prototypes for Exit actions
void EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Exit();

// Prototypes for Events handlers
void EDAP_STATE_SENSOR_0_timeout_Event_Handler(int timer_id);
void EDAP_STATE_SENSOR_0_voltage_value_Event_Handler(int v);
void EDAP_STATE_SENSOR_0_temperature_value_Event_Handler(int v);
void EDAP_STATE_SENSOR_0_receive_Event_Handler(int addr, char * msg, int msglen, int rssi, int lqi);

/******************************************************************************
 *                    IMPLEMENTATION OF ENTRY AND EXIT
 ******************************************************************************/
 
// Entry actions
void EDAP_STATE_SENSOR_0_EDAP_STATE_ACTIVE_1_On_Entry() {
	EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_ACTIVE_1] = EDAP_STATE_WAITING_4; // no history
	
	EDAP_STATE_SENSOR_0_EDAP_STATE_WAITING_4_On_Entry();
}
void EDAP_STATE_SENSOR_0_EDAP_STATE_INIT_2_On_Entry() {
	{
Timer_send_start(1, 1000);
LED_send_light_on(1);
LED_send_light_on(2);
sensor_id = 99;
RF2500_send_set_address(1);
RF2500_send_set_channel(7);
}
}
void EDAP_STATE_SENSOR_0_EDAP_STATE_CONTACT_GATEWAY_3_On_Entry() {
	{
buf[0] = 127;
buf[1] = sensor_id;
buf[2] = 0x0;
RF2500_send_transmit(0, buf);
}
}
void EDAP_STATE_SENSOR_0_EDAP_STATE_WAITING_4_On_Entry() {
	{
Timer_send_start(1, 1000);
LED_send_light_off(1);
RF2500_send_power_off();
}
}
void EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Entry() {
	{
LED_send_light_on(2);
MSP430Sensor_send_mesure_temperature();
}
}

// Exit actions
void EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Exit(){
	{
LED_send_light_off(2);
}
}

 /******************************************************************************
 *                    IMPLEMENTATION OF EVENT HANDLING
 ******************************************************************************/
 
void EDAP_STATE_SENSOR_0_timeout_Event_Handler(int timer_id){
		if ( EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] == EDAP_STATE_INIT_2 &&
		timer_id == 1 ) {
		
		LED_send_light_off(1);
		EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] = EDAP_STATE_CONTACT_GATEWAY_3; // change state
		EDAP_STATE_SENSOR_0_EDAP_STATE_CONTACT_GATEWAY_3_On_Entry();
		return; // The event has been consumed
	}
if ( EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_ACTIVE_1] == EDAP_STATE_WAITING_4 &&
		EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] == EDAP_STATE_ACTIVE_1 &&
		timer_id == 1 ) {
		
		{
PowerMgt_send_sleep_about5s();
LED_send_light_on(1);
}
		EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_ACTIVE_1] = EDAP_STATE_READSENSORVALUES_5; // change state
		EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Entry();
		return; // The event has been consumed
	}
}
void EDAP_STATE_SENSOR_0_voltage_value_Event_Handler(int v){
		if ( EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_ACTIVE_1] == EDAP_STATE_READSENSORVALUES_5 &&
		EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] == EDAP_STATE_ACTIVE_1 ) {
		EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Exit();
		{
batt = v;
buf[6] = 0xA0;
buf[7] = batt;
buf[8] = batt >> 8;
buf[9] = 0xFF;
RF2500_send_transmit(0, buf);
}
		EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_ACTIVE_1] = EDAP_STATE_WAITING_4; // change state
		EDAP_STATE_SENSOR_0_EDAP_STATE_WAITING_4_On_Entry();
		return; // The event has been consumed
	}
}
void EDAP_STATE_SENSOR_0_temperature_value_Event_Handler(int v){
	if ( EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_ACTIVE_1] == EDAP_STATE_READSENSORVALUES_5 &&
		EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] == EDAP_STATE_ACTIVE_1 ) {
		EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Exit();
		{
temp = v;
buf[0] = sensor_id;
buf[1] = 0xFF;
buf[2] = 0x10;
buf[3] = temp;
buf[4] = temp >> 8;
buf[5] = 0xFF;
MSP430Sensor_send_mesure_voltage();
}
		EDAP_STATE_SENSOR_0_EDAP_STATE_READSENSORVALUES_5_On_Entry();
		return; // The event has been consumed
	}
	}
void EDAP_STATE_SENSOR_0_receive_Event_Handler(int addr, char * msg, int msglen, int rssi, int lqi){
		if ( EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] == EDAP_STATE_CONTACT_GATEWAY_3 &&
		msg[0] == 126 ) {
		
		{
sensor_id = msg[1];
LED_send_light_off(2);
}
		EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] = EDAP_STATE_ACTIVE_1; // change state
		EDAP_STATE_SENSOR_0_EDAP_STATE_ACTIVE_1_On_Entry();
		return; // The event has been consumed
	}
}

 /******************************************************************************
 *                        INITIALISATION AND MAIN
 ******************************************************************************/

int main () {


	int i;
	// Stop watchdog timer
	WDTCTL = WDTPW + WDTHOLD;
	
	// Set the clock
	BCSCTL1 = CALBC1_8MHZ;
	DCOCTL = CALDCO_8MHZ;
	BCSCTL3 |= LFXT1S_2;


	
	// initialize devices
	init_LED();
	init_Timer();
	init_RF2500();
	init_PowerMgt();
	
	// register state machine event handlers
	register_Timer_receive_timeout_listener(EDAP_STATE_SENSOR_0_timeout_Event_Handler);
	register_MSP430Sensor_receive_voltage_value_listener(EDAP_STATE_SENSOR_0_voltage_value_Event_Handler);
	register_MSP430Sensor_receive_temperature_value_listener(EDAP_STATE_SENSOR_0_temperature_value_Event_Handler);
	register_RF2500_receive_receive_listener(EDAP_STATE_SENSOR_0_receive_Event_Handler);

	// Initialize state machine
	EDAP_STATE_SENSOR_0_Current_State[EDAP_STATE_SENSOR_0] = EDAP_STATE_INIT_2; // Set the initial state
	EDAP_STATE_SENSOR_0_EDAP_STATE_INIT_2_On_Entry();
	
	__enable_interrupt();  // IMPORTANT :-)
	
	while(1) {
		int i;
		
	// some sort of polling delay
	for(i=50000; i>0; i--) __no_operation();

		// poll the drivers
		poll_Timer();
		poll_RF2500();
		poll_MSP430Sensor();
	}
}
