
/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : LongPress 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"


#include  "msp430x22x4.h"
#include <signal.h>
#include <stdlib.h>
#include <string.h>


/******************************************************************************
 *                           INCLUDE THE DEVICES
 ******************************************************************************/
 
#include "Button.h" 
#include "Timer.h" 
#include "LED.h" 

/******************************************************************************
 *                      CODE FROM THE GLOBALS TEMPLATE
 ******************************************************************************/




/******************************************************************************
 *                            STATES DECLARATION
 ******************************************************************************/
// Define all the states and their IDs
#define EDAP_STATE_LONGPRESS_0 0	// fixed
#define EDAP_STATE_OFF_3 3
#define EDAP_STATE_BOOTING_4 4
#define EDAP_STATE_ON_1 1
#define EDAP_STATE_RUNNING_2 2
#define EDAP_STATE_IDLE_5 5
#define EDAP_STATE_BLINK_6 6
#define EDAP_STATE_PAUSE_7 7

// Static variable to store the current state of the state machines and composites
static int EDAP_STATE_LONGPRESS_0_Current_State[3];

/******************************************************************************
 *                          PROTOTYPES DECLARATION
 ******************************************************************************/

// Prototypes for Entry actions
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_OFF_3_On_Entry();
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BOOTING_4_On_Entry();
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_ON_1_On_Entry();
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_RUNNING_2_On_Entry();
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_IDLE_5_On_Entry();
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BLINK_6_On_Entry();

// Prototypes for Exit actions
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BOOTING_4_On_Exit();
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BLINK_6_On_Exit();

// Prototypes for Events handlers
void EDAP_STATE_LONGPRESS_0_press_Event_Handler(int button_id);
void EDAP_STATE_LONGPRESS_0_timeout_Event_Handler(int timer_id);
void EDAP_STATE_LONGPRESS_0_release_Event_Handler(int button_id);

/******************************************************************************
 *                    IMPLEMENTATION OF ENTRY AND EXIT
 ******************************************************************************/
 
// Entry actions
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_ON_1_On_Entry() {
	EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_ON_1] = EDAP_STATE_RUNNING_2; // no history
	
	EDAP_STATE_LONGPRESS_0_EDAP_STATE_RUNNING_2_On_Entry();
}
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_RUNNING_2_On_Entry() {
	EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_RUNNING_2] = EDAP_STATE_IDLE_5; // no history
	
	EDAP_STATE_LONGPRESS_0_EDAP_STATE_IDLE_5_On_Entry();
}
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_OFF_3_On_Entry() {
	{
LED_send_light_off(1);
LED_send_light_off(2);
}
}
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BOOTING_4_On_Entry() {
	{
LED_send_light_on(1);
LED_send_light_on(2);
}
}
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_IDLE_5_On_Entry() {
	{
Timer_send_start(2, 5);
}
}
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BLINK_6_On_Entry() {
	{
LED_send_light_on(2);
Timer_send_start(2, 5);
}
}

// Exit actions
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BOOTING_4_On_Exit(){
	{
LED_send_light_off(2);
}
}
void EDAP_STATE_LONGPRESS_0_EDAP_STATE_BLINK_6_On_Exit(){
	{
LED_send_light_off(2);
}
}

 /******************************************************************************
 *                    IMPLEMENTATION OF EVENT HANDLING
 ******************************************************************************/
 
void EDAP_STATE_LONGPRESS_0_press_Event_Handler(int button_id){
	if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_OFF_3 &&
		button_id == 1 ) {
		
		Timer_send_start(1, 30);
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_OFF_3_On_Entry();
		return; // The event has been consumed
	}
if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_ON_1 &&
		button_id == 1 ) {
		
		Timer_send_start(1, 30);
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_ON_1_On_Entry();
		return; // The event has been consumed
	}
	if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_ON_1] == EDAP_STATE_RUNNING_2 &&
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_ON_1 &&
		button_id == 1 ) {
		
		
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_ON_1] = EDAP_STATE_PAUSE_7; // change state
		
		return; // The event has been consumed
	}
if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_ON_1] == EDAP_STATE_PAUSE_7 &&
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_ON_1 &&
		button_id == 1 ) {
		
		
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_ON_1] = EDAP_STATE_RUNNING_2; // change state
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_RUNNING_2_On_Entry();
		return; // The event has been consumed
	}
}
void EDAP_STATE_LONGPRESS_0_timeout_Event_Handler(int timer_id){
		if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_OFF_3 &&
		timer_id == 1 ) {
		
		
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] = EDAP_STATE_BOOTING_4; // change state
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_BOOTING_4_On_Entry();
		return; // The event has been consumed
	}
if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_ON_1 &&
		timer_id == 1 ) {
		
		
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] = EDAP_STATE_OFF_3; // change state
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_OFF_3_On_Entry();
		return; // The event has been consumed
	}
if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_RUNNING_2] == EDAP_STATE_IDLE_5 &&
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_ON_1] == EDAP_STATE_RUNNING_2 &&
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_ON_1 &&
		timer_id == 2 ) {
		
		
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_RUNNING_2] = EDAP_STATE_BLINK_6; // change state
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_BLINK_6_On_Entry();
		return; // The event has been consumed
	}
if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_RUNNING_2] == EDAP_STATE_BLINK_6 &&
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_ON_1] == EDAP_STATE_RUNNING_2 &&
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_ON_1 &&
		timer_id == 2 ) {
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_BLINK_6_On_Exit();
		
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_RUNNING_2] = EDAP_STATE_IDLE_5; // change state
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_IDLE_5_On_Entry();
		return; // The event has been consumed
	}
}
void EDAP_STATE_LONGPRESS_0_release_Event_Handler(int button_id){
	if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_OFF_3 &&
		button_id == 1 ) {
		
		Timer_send_cancel(1);
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_OFF_3_On_Entry();
		return; // The event has been consumed
	}
if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_ON_1 &&
		button_id == 1 ) {
		
		Timer_send_cancel(1);
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_ON_1_On_Entry();
		return; // The event has been consumed
	}
	if ( EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] == EDAP_STATE_BOOTING_4 &&
		button_id == 1 ) {
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_BOOTING_4_On_Exit();
		
		EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] = EDAP_STATE_ON_1; // change state
		EDAP_STATE_LONGPRESS_0_EDAP_STATE_ON_1_On_Entry();
		return; // The event has been consumed
	}
}

 /******************************************************************************
 *                        INITIALISATION AND MAIN
 ******************************************************************************/

int main () {


	int i;
	// Stop watchdog timer
	WDTCTL = WDTPW + WDTHOLD;
	
	// Set the clock
	BCSCTL1 = CALBC1_8MHZ;
	DCOCTL = CALDCO_8MHZ;
	BCSCTL3 |= LFXT1S_2;


	
	// initialize devices
	init_Button();
	init_LED();
	init_Timer();
	
	// register state machine event handlers
	register_Button_receive_press_listener(EDAP_STATE_LONGPRESS_0_press_Event_Handler);
	register_Timer_receive_timeout_listener(EDAP_STATE_LONGPRESS_0_timeout_Event_Handler);
	register_Button_receive_release_listener(EDAP_STATE_LONGPRESS_0_release_Event_Handler);

	// Initialize state machine
	EDAP_STATE_LONGPRESS_0_Current_State[EDAP_STATE_LONGPRESS_0] = EDAP_STATE_OFF_3; // Set the initial state
	EDAP_STATE_LONGPRESS_0_EDAP_STATE_OFF_3_On_Entry();
	
	__enable_interrupt();  // IMPORTANT :-)
	
	while(1) {
		int i;
		
	// some sort of polling delay
	for(i=50000; i>0; i--) __no_operation();

		// poll the drivers
		poll_Button();
		poll_Timer();
	}
}
