/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : LED 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */

#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <inttypes.h>

#include "LED.h"

// Implemetation of void globals_LED()

void init_LED() {
// Implemetation of void init_LED()
	DDRC|= _BV(PC4); PORTC &= ~_BV(PC4); // output off
	DDRC|= _BV(PC5); PORTC &= ~_BV(PC5); // output off
}

void LED_send_light_on(int led_id) {
// Implemetation of void LED_send_light_on()

	switch(led_id) {
	case 1: PORTC |= _BV(PC4); // ON
		break;
	case 2: PORTC |= _BV(PC5); // ON
		break;
	default: break;
	}

}
void LED_send_light_off(int led_id) {
// Implemetation of void LED_send_light_off()

	switch(led_id) {
	case 1: PORTC &= ~_BV(PC4); // OFF
		break;
	case 2: PORTC &= ~_BV(PC5); // OFF
		break;
	default: break;
	}

}
void LED_send_toggle(int led_id) {
// Implemetation of void LED_send_toggle()

	switch(led_id) {
	case 1: PORTC ^= _BV(PC4); // TOGGLE
		break;
	case 2: PORTC ^= _BV(PC5); // TOGGLE
		break;
	default: break;
	}

}
