global java.util.Map uniqueobjects;
Rule "Aspect"
when
	$s0Decl: edap.StateMachine()
	$s1Decl: edap.State()
	$s2Decl: edap.Transition()
	$s3Decl: edap.State(name == "Idle")
	$s0: edap.StateMachine(this == $s0Decl, substate contains $s1Decl, substate contains $s3Decl)
	$s1: edap.State(this == $s1Decl, outgoing contains $s2Decl, outgoing contains $s2Decl)
	$s2: edap.Transition(this == $s2Decl, target == $s3Decl, source == $s1Decl, target == $s3Decl, source == $s1Decl)
	$s3: edap.State(this == $s3Decl, incoming contains $s2Decl, incoming contains $s2Decl)
then
	System.out.println("--------------------------------------");
	System.out.println("Any matches: "+$s1.getName()+" state");
	System.out.println("Any->Idle matches: "+$s2.getName()+" transition");
	
	System.out.println("Creating global state OFF...");
	edap.State off = (edap.State) uniqueobjects.get("off");
	if ( off == null){
		off = edap.EdapFactory.eINSTANCE.createState();
		off.setName("Off");
		uniqueobjects.put("off",off);
	}
	System.out.println("Done!");
	
	System.out.println("Creating per join point transition ->Off...");
	edap.Transition t = edap.EdapFactory.eINSTANCE.createTransition();
	t.setName($s1.getName()+"->Off");
	$s1.getOutgoing().add(t);
	System.out.println("Done!");
	
	System.out.println("Removing ->Idle transition...");
	//$s1.getOutgoing().remove($s2);
	System.out.println("Done!");
	
	System.out.println("Creating global Off->Idle transition...");
	edap.Transition toIdle = (edap.Transition) uniqueobjects.get("toIdle");
	if ( toIdle == null){
		toIdle = edap.EdapFactory.eINSTANCE.createTransition();
		toIdle.setName("Off->Idle");
		uniqueobjects.put("toIdle",toIdle);
	}
	off.getOutgoing().add(toIdle);
	$s0.getSubstate().add(off);
	System.out.println("Done!");
	System.out.println("--------------------------------------");
	System.out.println();
end
