/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : LED 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"

#ifndef LED_H_
#define LED_H_

void init_LED();


void LED_send_light_on(int led_id);
void LED_send_light_off(int led_id);
void LED_send_toggle(int led_id);


#endif /* LED_H_ */
