/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : Timer 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"

#include "Timer.h"

// Implemetation of void globals_Timer()

#define MAX_TIMERS 8

volatile long cpt;
volatile long timeouts[MAX_TIMERS];


void (*Timer_receive_timeout_listener)(int) = 0x0;
void register_Timer_receive_timeout_listener(void(*listener)(int)) {
	Timer_receive_timeout_listener = listener;
}
void Timer_receive_timeout(int timer_id) {
	if (Timer_receive_timeout_listener != 0) Timer_receive_timeout_listener(timer_id);
}

void init_Timer() {
// Implemetation of void init_Timer()

int i;
cpt = 0;
for(i=0; i<MAX_TIMERS; i++) timeouts[i] = 0;

}
void poll_Timer(){
// Implemetation of void poll_Timer()

int i;
int active = 0;
for(i=0; i<MAX_TIMERS; i++) {
	if (timeouts[i] != 0) {
		active = 1;
		if (timeouts[i] <= cpt) {
			timeouts[i] = 0;
			Timer_receive_timeout(i);
		}
	}
}
if (active)	cpt++;
else cpt = 0;

}
void Timer_send_start(int timer_id, int delay) {
// Implemetation of void Timer_send_start()

timeouts[timer_id] = cpt + delay;

}
void Timer_send_cancel(int timer_id) {
// Implemetation of void Timer_send_cancel()

timeouts[timer_id] = 0;

}
