<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edapuC"
    nsURI="http://edapuC" nsPrefix="edapuC">
  <eClassifiers xsi:type="ecore:EClass" name="UCGenerator" eSuperTypes="#//UCElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//UCDevice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//UCGenerator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edap" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../org.sintef.edap.model/model/edap.ecore#//EdapModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//UCApplication"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UCDevice" eSuperTypes="#//UCElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//UCMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="ecore:EClass ../../org.sintef.edap.model/model/edap.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="poll" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="global" eType="#//Template"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UCMessage" eSuperTypes="#//UCElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="ecore:EClass ../../org.sintef.edap.model/model/edap.ecore#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="send" eType="#//Template"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UCElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//StaticProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UCApplication" eSuperTypes="#//UCElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state_machine" lowerBound="1"
        eType="ecore:EClass ../../org.sintef.edap.model/model/edap.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headers" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="poll" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="global" eType="#//Template"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
