Rule "Aspect"
when
	$s0Decl: edap.StateMachine()
	$s1Decl: edap.State()
	$s2Decl: edap.Transition()
	$s3Decl: edap.State(name == "Idle")
	$s0: edap.StateMachine(this == $s0Decl, substate contains $s1Decl, substate contains $s3Decl)
	$s1: edap.State(this == $s1Decl, outgoing contains $s2Decl, outgoing contains $s2Decl)
	$s2: edap.Transition(this == $s2Decl, target == $s3Decl, source == $s1Decl, target == $s3Decl, source == $s1Decl)
	$s3: edap.State(this == $s3Decl, incoming contains $s2Decl, incoming contains $s2Decl)
then
	System.out.println("--------------------------------------");
	System.out.println("Any matches: "+$s1.getName()+" state");
	System.out.println("Any->Idle matches: "+$s2.getName()+" transition");
	
	
	edap.PlatformAnnotation annot = edap.EdapFactory.eINSTANCE.createPlatformAnnotation();
	annot.setName("xyz");
	annot.setValue("abc");
	
	$s2.getAnnotations().add(annot);
	
	
	System.out.println("--------------------------------------");
	System.out.println();
end
