/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : Button 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
#include <io.h>
#include <signal.h>

#include "Button.h"

// Implemetation of void globals_Button()

volatile int buttons_status;

int get_buttons_status() {
	int status = 0x0000;
	if ( P1IN & ( 1 << 3) ) status |= 1 << 0;
	return status;
}


void (*Button_receive_press_listener)(int) = 0x0;
void register_Button_receive_press_listener(void(*listener)(int)) {
	Button_receive_press_listener = listener;
}
void Button_receive_press(int button_id) {
	if (Button_receive_press_listener != 0) Button_receive_press_listener(button_id);
}
void (*Button_receive_release_listener)(int) = 0x0;
void register_Button_receive_release_listener(void(*listener)(int)) {
	Button_receive_release_listener = listener;
}
void Button_receive_release(int button_id) {
	if (Button_receive_release_listener != 0) Button_receive_release_listener(button_id);
}

void init_Button() {
// Implemetation of void init_Button()

	P1SEL &= ~(1 << 3); // use P1.3 as digital IO
	P1DIR &= ~(1 << 3); // input
	//P1REN |= (1 << 3); // pull-up?? does not work with this line
	buttons_status = get_buttons_status();

}
void poll_Button(){
// Implemetation of void poll_Button()

	int new_status = get_buttons_status();
	int diff = new_status ^ buttons_status;
	int i;
	for(i=0; i<1; i++) {
		if(diff>>i & 0x01) {
			if(new_status>>i & 0x01) {
				Button_receive_release(i+1);
			}
			else {
				Button_receive_press(i+1);
			}
		}
	}
	buttons_status = new_status;

}
