/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : LED 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"

#include "LED.h"

// Implemetation of void globals_LED()



void init_LED() {
// Implemetation of void init_LED()

	P1SEL &= ~(1 << 0); // use P1.0 as digital IO
	P1DIR |= (1 << 0); // output
	P1OUT &= ~(1 << 0); // OFF
	P1SEL &= ~(1 << 6); // use P1.1 as digital IO
	P1DIR |= (1 << 6); // output
	P1OUT &= ~(1 << 6); // OFF

}

void LED_send_light_on(int led_id) {
// Implemetation of void LED_send_light_on()

	switch(led_id) {
	case 1: P1OUT |= (1 << 0); // ON
		break;
	case 2: P1OUT |= (1 << 6); // ON
		break;
	default: break;
	}

}
void LED_send_light_off(int led_id) {
// Implemetation of void LED_send_light_off()

	switch(led_id) {
	case 1: P1OUT &= ~(1 << 0); // OFF
		break;
	case 2: P1OUT &= ~(1 << 6); // OFF
		break;
	default: break;
	}

}
void LED_send_toggle(int led_id) {
// Implemetation of void LED_send_toggle()

	switch(led_id) {
	case 1: P1OUT ^= (1 << 0); // TOGGLE
		break;
	case 2: P1OUT ^= (1 << 6); // TOGGLE
		break;
	default: break;
	}

}
