/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : PowerMgt 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"

#ifndef POWERMGT_H_
#define POWERMGT_H_

void init_PowerMgt();


void PowerMgt_send_sleep_about5s();
void PowerMgt_send_reset();


#endif /* POWERMGT_H_ */
