/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : Timer 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"

#ifndef TIMER_H_
#define TIMER_H_

void init_Timer();
void poll_Timer();

void Timer_send_start(int timer_id, int delay);
void Timer_send_cancel(int timer_id);

void register_Timer_receive_timeout_listener(void(*listener)(int));

#endif /* TIMER_H_ */
