/*
 * Generated using the EDAP MDE Framework (C)SINTEF
 *
 *     ****    DO NOT EDIT THIS FILE    ****
 *
 * Application : WTSClient 
 *    Platform : Texas Instruments MSP430 Microcontroller
 *        Date : ???
 *      Author : SINTEF
 *     License : EPL
 */
 #include  "msp430x22x4.h"

#ifndef WTSCLIENT_H_
#define WTSCLIENT_H_

void init_WTSClient();
void poll_WTSClient();

void WTSClient_send_SensorData(int temp, int min, int max, int batt);
void WTSClient_send_SensorStatus(int interval, int min_alarm, int max_alarm, int batt_alarm);
void WTSClient_send_SensorName(char * name);

void register_WTSClient_receive_GetData_listener(void(*listener)());
void register_WTSClient_receive_GetStatus_listener(void(*listener)());
void register_WTSClient_receive_GetName_listener(void(*listener)());
void register_WTSClient_receive_ResetMinMax_listener(void(*listener)());
void register_WTSClient_receive_SetMinAlarm_listener(void(*listener)(int));
void register_WTSClient_receive_SetMaxAlarm_listener(void(*listener)(int));
void register_WTSClient_receive_SetBattAlarm_listener(void(*listener)(int));
void register_WTSClient_receive_SetInterval_listener(void(*listener)(int));
void register_WTSClient_receive_SetName_listener(void(*listener)(char *));

#endif /* WTSCLIENT_H_ */
